/** @format */

import { Toaster } from "@/common/components";
// import { ToastProvider } from "@/common/components/search-bar/provider/toast-provider";
import { ThemeProvider } from "@/common/components/theme/theme-provider";
import localFont from "next/font/local";
import "../common/styles/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange>
          {children}
          {/* <ToastProvider /> */}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
